# Generated by Django 5.2.11 on 2026-02-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='colleges/'),
        ),
        migrations.AlterField(
            model_name='college',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='colleges/'),
        ),
    ]
